import type { TrekPackage } from "./trip-packages"; // type-only — no runtime cycle
import {
  ABC_ADDONS,
  ABC_EXCLUSIONS,
  ABC_INCLUDE_NOTE,
  ABC_INCLUSIONS,
  ABC_ITINERARY,
  ABC_ITINERARY_INTRO,
  ABC_LUKLA_NOTE,
  ABC_SLUG,
} from "./abc-luxury-content";

const IMG = "/images/nepal/nepal-trek-abc.webp";

/** Default published Annapurna Base Camp Luxury Trek — merged with CMS unless a full custom save exists. */
export const ABC_LUXURY_TRIP_PACKAGE: TrekPackage = {
  id: "abc-lux",
  catalogId: "abc-lux",
  slug: ABC_SLUG,
  country: "nepal",
  status: "published",
  featured: true,
  badge: "Best Seller",
  title: "Annapurna Base Camp Luxury Trek",
  subtitle: "A private sanctuary walk through rhododendron forests to the foot of Annapurna.",
  duration: "12 Days / 11 Nights",
  days: 12,
  difficulty: "Moderate",
  destination: "Nepal · Annapurna Sanctuary",
  maxAltitude: "4,130 m / 13,550 ft",
  maxAltitudeFt: "13,550 ft",
  countryLabel: "Nepal",
  activityLabel: "Private luxury trek",
  accommodationLabel: "Luxury hotels + premium mountain lodges",
  mealsLabel: "As per itinerary",
  startEndLabel: "Kathmandu",
  groupSize: "Private · 2–10 guests",
  bestSeason: "March–May · September–November",
  priceUsd: 2180,
  groupPrices: [
    { id: "p1", label: "1 Pax", priceUsd: 2380 },
    { id: "p2", label: "2–3 Pax", priceUsd: 2180 },
    { id: "p3", label: "4–9 Pax", priceUsd: 2050 },
    { id: "p4", label: "10–14 Pax", priceUsd: 1920 },
  ],
  overview:
    "The Annapurna Base Camp Luxury Trek is Ambition Holidays’ twelve-day private journey into the sanctuary — Kathmandu culture, Pokhara’s lakeside calm, then a measured walk through Gurung villages, bamboo forest and alpine basin to 4,130 m beneath Annapurna I, Annapurna South, Hiunchuli and Machapuchare. The walking is moderate: long days on stone steps and forest trail, but no technical climbing and no Lukla lottery. We book the best lodges available on the route, keep group sizes small, and pair the ascent with honest pacing so the sanctuary sunrise feels earned rather than rushed. Sister company Ambition Himalaya Treks and Expeditions has worked the Annapurna for more than a decade; this programme layers private transfers, upgraded hotel nights and a dedicated guide team on that same corridor.",
  highlights: [
    "Twelve days from Kathmandu to Annapurna Base Camp with private road transfers and lakeside hotel nights in Pokhara.",
    "Walk through Ghandruk and Chhomrong — stone villages with direct views of Annapurna South and Machapuchare.",
    "Enter the Modi Khola gorge: bamboo, rhododendron and waterfall days that feel far from the road.",
    "Sleep inside the Annapurna Sanctuary amphitheatre at 4,130 m with the full ring of peaks above camp.",
    "Sunrise from Base Camp before the long descent — light on ice and granite you cannot see from Pokhara.",
    "Natural hot springs at Jhinu Danda after the high nights — a quiet reward before returning to the lake.",
    "ACAP permit and TIMS handled before you leave Kathmandu; no queueing at the trail gate.",
    "Kathmandu valley sightseeing with Pashupatinath, Boudhanath and Swayambhunath on Day 2.",
  ],
  inclusions: ABC_INCLUSIONS,
  exclusions: ABC_EXCLUSIONS,
  gallery: [
    IMG,
    "/images/packages/annapurna-v2.webp",
    "/images/nepal/nepal-cover.webp",
    "/images/journal/annapurna-clean.webp",
    "/images/packages/annapurna-circuit.webp",
    "/images/nepal/nepal-trek-manaslu.webp",
  ],
  tripGalleryTitle: "Trip Gallery",
  galleryAlts: [
    "Machapuchare above the Annapurna Sanctuary",
    "Annapurna peaks from the sanctuary trail",
    "Nepal Himalayan foothills",
    "Traveller overlooking Annapurna ridges",
    "High Annapurna circuit scenery",
    "Forest trail in the Nepal Himalaya",
  ],
  heroSrc: IMG,
  heroAlt: "Machapuchare above the Annapurna Sanctuary",
  altitudeChartM: "",
  altitudeChartFt: "",
  altitudeGainSrc: "",
  routeMapSrc: "/images/packages/annapurna-v2.webp",
  weatherDailySrc: "",
  weatherMonthlySrc: "",
  routeMapFile: "annapurna-base-camp-luxury-trek-route-map",
  altitudeMFile: "annapurna-base-camp-luxury-trek-altitude-meters",
  altitudeFtFile: "annapurna-base-camp-luxury-trek-altitude-feet",
  weatherDailyFile: "annapurna-base-camp-luxury-trek-daily-temperature",
  weatherMonthlyFile: "annapurna-base-camp-luxury-trek-monthly-temperature",
  itineraryIntro: ABC_ITINERARY_INTRO,
  itinerary: ABC_ITINERARY,
  faqs: [
    {
      q: "How difficult is the Annapurna Base Camp Luxury Trek?",
      a: "Moderate. Expect five to six hours on most walking days with stone steps and forest. The highest sleep is Annapurna Base Camp at 4,130 m. Fitness matters; technical skills do not. Guests who already hike regularly and respect altitude finish comfortably.",
    },
    {
      q: "What is the highest point?",
      a: "Annapurna Base Camp at 4,130 m / 13,550 ft. Machapuchare Base Camp is crossed on the way in. There is no glacier climbing — you walk to the camp and back.",
    },
    {
      q: "When is the best time to go?",
      a: "March to May for rhododendron and clear ridges; September to November for crisp air and sharp peaks. Winter is possible for experienced walkers who accept cold lodges. Monsoon (June–August) brings cloud, leeches in the forest and slick stone — we do not sell it as a luxury window.",
    },
    {
      q: "Which permits are required?",
      a: "Annapurna Conservation Area Permit (ACAP) and TIMS. Ambition Holidays arranges both before you leave Kathmandu.",
    },
    {
      q: "Do I need a flight to Lukla?",
      a: "No. This route uses road transfers to Pokhara and private vehicles to trailheads. Optional flights between Kathmandu and Pokhara can shorten travel when weather allows.",
    },
    {
      q: "What does luxury mean on this trek?",
      a: "Premium Kathmandu and Pokhara hotel nights, selected mountain lodges on the trail, private transfers, a dedicated guide and porter support. Above Deurali the buildings are simpler because that is the mountain — we do not promise five-star walls inside the sanctuary.",
    },
    {
      q: "Is travel insurance required?",
      a: "Yes. Your policy must cover trekking to at least 4,500 m and helicopter evacuation. We cannot put you on the trail without proof of cover.",
    },
    {
      q: "Can beginners join?",
      a: "Yes, if you can walk four to six hours on uneven ground several weeks before you fly and you will listen when the guide slows the pace. Previous high-altitude trekking helps but is not mandatory.",
    },
  ],
  whyItems: [
    {
      title: "Sanctuary specialists",
      body: "Your lead guide knows the Modi Khola steps, the Chhomrong descent, and how fast the weather closes in above Deurali. Briefings are in person — route, kit, altitude, lodge plan — not a PDF the night before.",
    },
    {
      title: "Lakeside bookends",
      body: "Pokhara nights are part of the design. You enter the hills rested and return to a real hotel before Kathmandu — not a rushed drive straight to the airport.",
    },
    {
      title: "Lodges chosen, not random",
      body: "We reserve the best available rooms on the ABC corridor each season. In peak weeks that means booking early; your confirmation lists the lodge standard we target.",
    },
    {
      title: "Pacing without ego",
      body: "Nobody on the team is paid to drag you to Base Camp if the night went badly. We turn around when altitude says so. The sanctuary is the goal; safety is the rule.",
    },
    {
      title: "Permits done in Kathmandu",
      body: "ACAP and TIMS are on your file before the private vehicle leaves for Pokhara. You walk through the check post with paperwork already stamped.",
    },
    {
      title: "Sister-company depth",
      body: "Ambition Himalaya Treks and Expeditions has guided the Annapurna for more than ten years. Ambition Holidays adds private logistics and quieter ratios on the same trail.",
    },
  ],
  weatherBody:
    "Spring (March–May) paints the lower forest in rhododendron and keeps afternoons warmer on the steps to Chhomrong. Autumn (September–November) trades flowers for the sharpest views of Machapuchare and the south face of Annapurna. Winter treks are quiet but cold above Bamboo. Monsoon moisture rises from Pokhara — cloud, rain and leeches below 2,500 m make June–August a poor fit for a luxury-labelled walk.",
  altitudeBody:
    "You sleep no higher than Annapurna Base Camp at 4,130 m. The gain is steady rather than extreme, but the sanctuary is still thin air. Drink more than you think you need, eat even when appetite fades, and tell your guide if sleep or headache changes. There is no helicopter shortcut through the amphitheatre — the correct response to serious altitude illness is descent, not a faster ascent.",
  packingItems: [
    "Broken-in waterproof boots and trekking socks",
    "Layered clothing: base, fleece, down jacket, waterproof shell",
    "Sleeping bag rated to −10 °C for lodge nights (rental available)",
    "Daypack 30–35 L with rain cover",
    "Trekking poles for stone steps and descent days",
    "Sun hat, warm beanie, UV sunglasses",
    "Headlamp, refillable bottles, purification tablets",
    "Personal first aid and prescribed medicines",
  ],
  packingIntro:
    "Pack for forest heat and sanctuary cold in the same week. We issue a porter duffel at the Kathmandu briefing (20 kg cap). Down jackets and sleeping bags can be rented if you prefer not to fly with bulk.",
  packingGroups: [
    {
      id: "abc-general",
      title: "Core kit",
      items: [
        "Four-season sleeping bag or rental from Kathmandu",
        "Down jacket; rental available",
        "Daypack with rain cover",
        "Broken-in waterproof boots",
      ],
    },
    {
      id: "abc-layers",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece or light insulated mid-layer",
        "Waterproof jacket and trousers",
        "Trekking trousers and one soft evening set",
        "Warm hat and gloves for Base Camp morning",
      ],
    },
    {
      id: "abc-trail",
      title: "On the trail",
      items: [
        "Trekking poles",
        "Two-litre water capacity plus purification",
        "High-SPF sunscreen and lip balm",
        "Small towel and toiletries",
        "Passport copies and insurance certificate",
      ],
    },
  ],
  suitableBody:
    "This trek suits guests who enjoy long walking days on stone and forest trail and who will communicate honestly about how they feel above 3,000 m. It is not a climb. Couples, families with trekking teenagers, and private friends’ groups all walk it when the pace stays human. If stairs wind you after twenty minutes, build that fitness before you book.",
  trainingBody:
    "Walk hills with a daypack three or four times a week in the two months before departure. Include long stair sessions — Chhomrong’s steps are the real training test. Cardio that lasts forty-five minutes matters more than gym mirrors. If you can manage six hours on feet with breaks, you are in the right zone.",
  khumbuBody:
    "The Annapurna Sanctuary is a glacial basin walled by Annapurna I (8,091 m), Annapurna South, Hiunchuli and the sacred fishtail of Machapuchare. Below Deurali the trail is forest and river; inside the basin it is open moraine and vertical granite. Gurung villages on the approach still farm terraces and host guests in stone lodges. You are inside a conservation area, not a national park queue — respect firewood limits and leave no trace above the tree line.",
  flightBody:
    "Standard programme uses private road transfer between Kathmandu and Pokhara (about 200 km). Optional domestic flights save a day when the weather window is open; we quote the fare and baggage rules before you confirm.",
  bufferBody:
    "Hold one spare day at the end of your international ticket if you choose flights on the Kathmandu–Pokhara leg. Road transfers are more predictable but can slow during landslide season (July–September).",
  heliBody:
    "Helicopter charters from Pokhara or the sanctuary are available for emergencies or private panorama flights — priced per aircraft and weather. This remains a walking itinerary unless you ask us to redesign it.",
  beforeItems: [
    "Travel insurance with helicopter evacuation is mandatory before Day 4.",
    "You will not summit Annapurna I. This trek ends at Base Camp inside the sanctuary.",
    "Rooms on trek are twin-sharing unless you pay for a private room where lodges offer one.",
    "Porter loads are capped at 20 kg per duffel.",
    "Hot showers and charging are lodge extras on many nights.",
    "Tips for guide and porter are customary and entirely your choice at the end.",
  ],
  permitsLabel: "ACAP + TIMS",
  regionLabel: "Annapurna Sanctuary",
  startLabel: "Kathmandu → Pokhara → ABC",
  metaTitle: "Annapurna Base Camp Luxury Trek 12 Days | Ambition Holidays",
  metaDescription:
    "Private 12-day Annapurna Base Camp luxury trek to 4,130 m. Moderate sanctuary walk via Ghandruk, Chhomrong and Pokhara lakeside hotels. Ambition Holidays, Kathmandu.",
  metaKeywords:
    "Annapurna Base Camp luxury trek, ABC trek 12 days, private lodge Annapurna, Machapuchare sanctuary, Pokhara, Ambition Holidays Nepal",
  focusKeyword: "Annapurna Base Camp luxury trek",
  tripadvisorLabel: "Excellent",
  tripadvisorScore: "5.0",
  tripadvisorCount: "140+ Reviews",
  tripadvisorHref: "https://www.tripadvisor.com",
  tripadvisorLogoSrc: "/images/reviews/tripadvisor-owl.png",
  googleLabel: "Excellent",
  googleScore: "5.0",
  googleCount: "165+ Reviews",
  googleHref: "https://www.google.com/maps",
  watchVideo: {
    id: "abc-watch",
    title: "Watch the trail",
    subtitle: "Annapurna Base Camp Luxury Trek",
    duration: "03:52",
    imageSrc: "/images/journal/annapurna-clean.webp",
    imageAlt: "Annapurna sanctuary ridge at dawn",
    videoSrc: "",
  },
  videoReviews: [
    {
      id: "vr-abc",
      title: "Annapurna Base Camp",
      subtitle: "12-day sanctuary walk",
      duration: "03:52",
      imageSrc: "/images/journal/annapurna-clean.webp",
      imageAlt: "Annapurna peaks from the trail",
      videoSrc: "",
    },
    {
      id: "vr-pokhara",
      title: "Pokhara to the foothills",
      subtitle: "Guest film",
      duration: "02:40",
      imageSrc: IMG,
      imageAlt: "Machapuchare from the Annapurna trail",
      videoSrc: "",
    },
  ],
  reviews: [
    {
      id: "g-abc-sarah",
      platform: "google",
      name: "Sarah L",
      avatarSrc: "",
      rating: 5,
      dateLabel: "5 months ago",
      meta: "12 reviews",
      title: "",
      body: "The sanctuary sunrise was worth every step on the Chhomrong stairs. Lodges were the best available each night and the Pokhara finish felt like a real holiday.",
    },
    {
      id: "g-abc-mark",
      platform: "google",
      name: "Mark T",
      avatarSrc: "",
      rating: 5,
      dateLabel: "8 months ago",
      meta: "Local Guide · 9 reviews",
      title: "",
      body: "Private pacing made the 4,130 m night manageable. Guide checked in every afternoon about altitude — no pressure to push when the headache appeared.",
    },
  ],
  tripInfoTitle: "Annapurna Base Camp Luxury Trek – Trip Information",
  tripInfo: [
    {
      id: "ti-season",
      title: "Best season",
      body: "March to May and September to November are the windows we recommend for this sanctuary walk. Spring adds rhododendron colour on the approach; autumn brings the clearest Machapuchare profiles. Winter is quieter and cold above Bamboo. Monsoon is cloud, rain on stone steps and leeches in the forest — not aligned with a luxury-paced itinerary.",
    },
    {
      id: "ti-elev",
      title: "Elevation & distance",
      body: "Annapurna Base Camp sits at 4,130 m inside the sanctuary. The walking line from Ghandruk through Chhomrong, Bamboo, Deurali and back is roughly 80–90 km depending on the exact lodge stops. Kathmandu and Pokhara nights sit near 1,400 m and 822 m respectively.",
    },
    {
      id: "ti-diff",
      title: "Difficulty",
      body: "Moderate. Long days on stone steps and forest trail without technical climbing. The Chhomrong descent and ascent test knees more than lungs until Deurali. Luxury here means hotel bookends and selected lodges — not a shortened trail.",
    },
    {
      id: "ti-acc",
      title: "Accommodation",
      body: "Luxury hotels in Kathmandu and Pokhara; premium or best-available mountain lodges from Ghandruk through the sanctuary and on the descent to Jhinu Danda. Rooms are twin-sharing unless you request a single supplement where lodges can provide one.",
    },
    {
      id: "ti-meals",
      title: "Meals",
      body: "Breakfast in hotels; full board on trekking days as listed in the itinerary. Lodge menus blend Nepali, Tibetan and simple international dishes. Vegetarian and most common dietary needs are accommodated when we know at booking.",
    },
    {
      id: "ti-transport",
      title: "Transportation",
      body: "Private airport transfers, Kathmandu–Pokhara–Kathmandu by road (included), and private vehicles to trailheads. Optional domestic flights on that sector can be added.",
    },
    {
      id: "ti-safety",
      title: "Trek safety & altitude",
      body: "Guides carry a group first-aid kit and monitor pace, hydration and sleep. Serious altitude symptoms mean descent — not a faster push to Base Camp. Your insurance must fund helicopter evacuation if required.",
    },
    {
      id: "ti-permits",
      title: "Permits",
      body: "Annapurna Conservation Area Permit and TIMS are included and arranged in Kathmandu before you travel to Pokhara.",
    },
    {
      id: "ti-lux",
      title: "Optional luxury upgrades",
      body: "Flight instead of road between Kathmandu and Pokhara, extra hotel nights, spa time in Pokhara, helicopter panorama, or a Chitwan extension. Quote at booking so rooms and guides are held.",
    },
  ],
  optionalAddons: ABC_ADDONS,
  includeNote: ABC_INCLUDE_NOTE,
  luklaNote: ABC_LUKLA_NOTE,
  reviewsWallpaperSrc: "/images/atmosphere/ebc-premium-section.webp",
  ogTitle: "",
  ogDescription: "",
  ogImageSrc: "",
};
