import type { NepalContent, NepalPackage } from "@/lib/nepal-defaults";

const CONTACT = "/contact";

function pkg(
  id: string,
  title: string,
  days: number,
  imageSrc: string,
  imageAlt: string,
  subtitle: string,
  difficulty: string,
  description: string,
  badge: string,
): NepalPackage {
  return {
    id,
    title,
    days,
    subtitle,
    difficulty,
    description,
    badge,
    href: `${CONTACT}?interest=${id}`,
    imageSrc,
    imageAlt,
  };
}

export const DEFAULT_BHUTAN: NepalContent = {
  visible: true,
  coverSrc: "/images/bhutan/bhutan-cover.webp",
  wallpaperSrc: "/images/bhutan/bhutan-cover.webp",
  eyebrow: "Destination",
  headline: "Bhutan",
  coverLead: "Luxury journeys through the Kingdom of Happiness — dzongs, festivals and Himalayan trails.",
  catalogEyebrow: "Private journeys",
  catalogHeadline: "Luxury Bhutan Packages",
  catalogLead:
    "Eight handcrafted itineraries — cultural lodges in Paro, Thimphu and Punakha, plus private Himalayan treks.",
  tabHint: "",
  ctaLabel: "Plan this journey",
  ctaHref: CONTACT,
  closeTitle: "Craft it privately",
  closeBody:
    "Ambition Holidays designs every Bhutan journey from Thamel, Kathmandu — sister company of Ambition Himalaya Treks and Expeditions. We arrange licensed Bhutan partners, lodges and festival dates around your private itinerary.",
  metaTitle: "Luxury Bhutan Tours & Treks | Ambition Holidays",
  metaDescription:
    "Luxury Bhutan packages by Ambition Holidays: Paro, Thimphu, Punakha, Taktsang, festivals, Druk Path and Himalayan treks. Sister company of Ambition Himalaya Treks and Expeditions.",
  categories: [
    {
      id: "cultural",
      label: "Luxury Cultural Journeys",
      countLabel: "6 Packages",
      packages: [
        pkg(
          "paro-thimphu-lux",
          "Paro & Thimphu Luxury Journey",
          6,
          "/images/bhutan/bhutan-paro-thimphu.webp",
          "Paro dzong and Thimphu valley at dusk",
          "Twin capitals, boutique lodges",
          "Easy",
          "Paro’s valley temples and Thimphu’s living capital, paced with private lodges.",
          "Most Popular",
        ),
        pkg(
          "taktsang-lux",
          "Paro Taktsang Luxury Tour",
          5,
          "/images/bhutan/bhutan-taktsang.webp",
          "Tiger's Nest monastery on the Paro cliff at sunrise",
          "Tiger’s Nest and Paro valley",
          "Moderate",
          "The cliff walk to Taktsang, with quiet Paro nights and a private guide.",
          "Best Seller",
        ),
        pkg(
          "thimphu-punakha-lux",
          "Thimphu & Punakha Luxury Escape",
          7,
          "/images/bhutan/bhutan-thimphu-punakha.webp",
          "Punakha Dzong at the river confluence",
          "Dochula pass to the Pho Chhu",
          "Easy",
          "From Thimphu over Dochula to Punakha Dzong at the river confluence.",
          "Exclusive",
        ),
        pkg(
          "punakha-valley-lux",
          "Punakha Valley Luxury Tour",
          6,
          "/images/bhutan/bhutan-punakha-valley.webp",
          "Punakha Valley rice terraces and dzong",
          "Rice terraces and riverside dzong",
          "Easy",
          "Punakha’s rice valley, riverside walks and a slower luxury lodge rhythm.",
          "Hidden Gem",
        ),
        pkg(
          "heritage-lux",
          "Bhutan Cultural Heritage Luxury Tour",
          9,
          "/images/bhutan/bhutan-heritage.webp",
          "Bhutan heritage dzongs and prayer flags",
          "Dzongs, temples and highland culture",
          "Easy",
          "Dzongs, temples and highland culture across western Bhutan at a private pace.",
          "Best Seller",
        ),
        pkg(
          "festival-lux",
          "Bhutan Festival & Culture Luxury Journey",
          10,
          "/images/bhutan/bhutan-festival.webp",
          "Bhutan tshechu festival dancers at a dzong",
          "Tshechu masks and sacred courtyards",
          "Easy",
          "Time a tshechu with lodge nights — masks, courtyards and living Himalayan faith.",
          "Exclusive",
        ),
      ],
    },
    {
      id: "trekking",
      label: "Luxury Trekking",
      countLabel: "2 Packages",
      packages: [
        pkg(
          "druk-path-lux",
          "Druk Path Luxury Trek",
          8,
          "/images/bhutan/bhutan-druk-path.webp",
          "Druk Path ridge lakes and fir forest in Bhutan",
          "High lakes between Paro and Thimphu",
          "Moderate",
          "The classic high-ridge walk between Paro and Thimphu, with luxury camp support.",
          "Most Popular",
        ),
        pkg(
          "bhutan-himalaya-lux",
          "Bhutan Himalayan Luxury Trek",
          10,
          "/images/bhutan/bhutan-himalaya-trek.webp",
          "Bhutan Himalayan peaks and alpine meadow",
          "High Himalaya, private pacing",
          "Challenging",
          "A longer Himalayan line in Bhutan — alpine meadows, snow peaks and private pacing.",
          "Exclusive",
        ),
      ],
    },
  ],
};
