export const EBC_ITINERARY_INTRO =
  "Experience the legendary Everest Base Camp journey with a more personalized and comfortable approach. This 14-day luxury trek combines the classic Khumbu trail with premium Kathmandu nights, private transfers, an experienced trekking team, planned acclimatization and the best available mountain lodges along the route.";

export const EBC_ITINERARY = [
  {
    id: "d1",
    day: 1,
    title: "Arrive in Kathmandu – private transfer & luxury hotel",
    altitude: "1,300 m / 4,265 ft",
    duration: "Airport transfer",
    distance: "Private transfer",
    meals: "Welcome dinner",
    stay: "Luxury hotel, Kathmandu",
    body: "Welcome to Nepal and the beginning of your Everest Base Camp Luxury Trek.\n\nUpon arrival at Tribhuvan International Airport, an Ambition Holidays representative meets you personally and provides a comfortable private transfer to your luxury hotel in the city.\n\nAfter check-in, recover from the flight. Depending on arrival time you may walk Thamel, use the hotel, or simply rest.\n\nIn the evening we host a welcome dinner of authentic Nepali cuisine — and you meet your guide and support team. The briefing covers the route, daily walking, altitude, lodges and preparations for the Khumbu.",
  },
  {
    id: "d2",
    day: 2,
    title: "Kathmandu Valley sightseeing & trek preparation",
    altitude: "1,300 m / 4,265 ft",
    duration: "Private sightseeing",
    distance: "Valley touring",
    meals: "Breakfast",
    stay: "Luxury hotel, Kathmandu",
    body: "After a relaxed hotel breakfast, a private sightseeing day through the Kathmandu Valley.\n\nVisit Pashupatinath Temple, Boudhanath Stupa and Swayambhunath (the Monkey Temple) on the hill above the valley — Hindu and Buddhist landmarks that set the cultural tone before the trail.\n\nReturn to the hotel for leisure time. In the afternoon your guide checks equipment and personal kit, then briefs altitude, weather, daily rhythm and the luxury services arranged on the journey.\n\nA comfortable hotel evening before the Himalayan portion begins.",
  },
  {
    id: "d3",
    day: 3,
    title: "Fly Kathmandu to Lukla & trek to Phakding",
    altitude: "Lukla 2,860 m / Phakding 2,610 m",
    duration: "3–4 hours walking",
    distance: "Approximately 8 km",
    meals: "Breakfast, lunch & dinner",
    stay: "Premium / best available lodge, Phakding",
    body: "Early breakfast, then the scenic mountain flight to Tenzing-Hillary Airport in Lukla — aerial Himalaya all the way in.\n\nMeet the trekking crew, organise bags, then walk downhill through the Dudh Koshi valley: settlements, forest and suspension bridges. The first walking day is kept honest so the body can begin the Khumbu.\n\nArrive Phakding beside the river after about 3–4 hours. Warm meal, quiet lodge night.",
  },
  {
    id: "d4",
    day: 4,
    title: "Phakding to Namche Bazaar",
    altitude: "3,440 m / 11,286 ft",
    duration: "5–7 hours walking",
    distance: "Approximately 10–12 km",
    meals: "Breakfast, lunch & dinner",
    stay: "Premium lodge, Namche Bazaar",
    body: "Deeper into the Everest region toward Namche Bazaar, the Sherpa trading and cultural centre of the Khumbu.\n\nPine and rhododendron, prayer-flag bridges, Monjo, then Sagarmatha National Park. From Jorsale the trail follows the river before the steeper climb to Namche. Peaks begin to show; the region announces itself.\n\nArrive 3,440 m after 5–7 hours. Premium lodge, warm drink, easy evening.",
  },
  {
    id: "d5",
    day: 5,
    title: "Namche acclimatization – Everest View & Sherpa town",
    altitude: "Hike ~3,880 m · sleep 3,440 m",
    duration: "3–4 hours walking",
    distance: "Approximately 4–6 km",
    meals: "Breakfast, lunch & dinner",
    stay: "Premium lodge, Namche Bazaar",
    body: "An essential acclimatization day. We do not rush higher.\n\nA gradual hike toward Syangboche and Hotel Everest View for Everest, Ama Dablam, Lhotse, Thamserku and Kongde. Photograph, sit with a warm drink, then descend to Namche.\n\nAfternoon at leisure: shops, cafés, Sherpa lanes, or the lodge. This extra night at altitude prepares the days above.",
  },
  {
    id: "d6",
    day: 6,
    title: "Namche Bazaar to Tengboche",
    altitude: "3,860 m / 12,664 ft",
    duration: "5–6 hours walking",
    distance: "Approximately 10–11 km",
    meals: "Breakfast, lunch & dinner",
    stay: "Premium / best available lodge, Tengboche",
    body: "One of the great scenic days: Everest, Lhotse, Nuptse, Ama Dablam, Thamserku and Kangtega on the high contour, then down to Phunki Tenga and up through rhododendron and pine to Tengboche at about 3,860 m.\n\nIf the gompa is open, sit quietly in Tengboche Monastery. Evening under a Himalayan skyline.",
  },
  {
    id: "d7",
    day: 7,
    title: "Tengboche to Dingboche",
    altitude: "4,410 m / 14,468 ft",
    duration: "5–6 hours walking",
    distance: "Approximately 10–12 km",
    meals: "Breakfast, lunch & dinner",
    stay: "Premium / best available lodge, Dingboche",
    body: "Forest, Sherpa settlements, Pangboche — one of the oldest villages in the region — then alpine pasture as trees thin. Ama Dablam stays on the skyline; Island Peak and Lhotse grow.\n\nArrive Dingboche 4,410 m after 5–6 hours. Best available premium lodge. Evening kept quiet because the air is thinner.",
  },
  {
    id: "d8",
    day: 8,
    title: "Dingboche acclimatization – Nangkartshang viewpoint",
    altitude: "Sleep 4,410 m / 14,468 ft",
    duration: "4–5 hours walking",
    distance: "Approximately 4–6 km",
    meals: "Breakfast, lunch & dinner",
    stay: "Premium / best available lodge, Dingboche",
    body: "Second acclimatization day. A gradual hike toward Nangkartshang / Nagarjun above the village — Ama Dablam, Lhotse, Makalu, Island Peak when weather allows.\n\nThe point is not a summit; it is sleep-high-walk-higher, then back to the same lodge. Afternoon for rest, reading, photographs. This night matters as much as Base Camp day.",
  },
  {
    id: "d9",
    day: 9,
    title: "Dingboche to Lobuche",
    altitude: "4,910 m / 16,109 ft",
    duration: "5–6 hours walking",
    distance: "Approximately 8–10 km",
    meals: "Breakfast, lunch & dinner",
    stay: "Best available premium lodge, Lobuche",
    body: "High alpine climbing toward Duglha, then the memorials for climbers lost on Everest — a quiet stretch of the trail. Sparse vegetation, big peaks.\n\nArrive Lobuche around 4,910 m after 5–6 hours. Dinner and an early night: tomorrow is Base Camp day.",
  },
  {
    id: "d10",
    day: 10,
    title: "Lobuche to Gorakshep – Everest Base Camp – return Gorakshep",
    altitude: "Base Camp 5,364 m / sleep Gorakshep 5,164 m",
    duration: "8–9 hours walking",
    distance: "Approximately 14–15 km",
    meals: "Breakfast, lunch & dinner",
    stay: "Best available lodge, Gorakshep",
    body: "The day most guests came for. Early from Lobuche along the Khumbu Glacier to Gorakshep, a short rest, then out to Everest Base Camp at about 5,364 m.\n\nCelebrate, photograph, then return to Gorakshep for a warm meal and sleep. The terrain is rugged; the guide keeps the pace honest.",
  },
  {
    id: "d11",
    day: 11,
    title: "Sunrise Kala Patthar, descend to Pheriche",
    altitude: "Kala Patthar 5,545 m / Pheriche ~4,240 m",
    duration: "7–8 hours walking",
    distance: "High viewpoint then descent",
    meals: "Breakfast, lunch & dinner",
    stay: "Premium / best available lodge, Pheriche",
    body: "Predawn climb to Kala Patthar — the viewpoint Base Camp cannot give. Everest, Nuptse, Pumori, Ama Dablam in first light.\n\nDescend to Gorakshep for breakfast, then continue down to Pheriche. Lower air, a wider valley, a lodge evening that usually sleeps better than the glacier.",
  },
  {
    id: "d12",
    day: 12,
    title: "Pheriche to Namche Bazaar",
    altitude: "3,440 m / 11,286 ft",
    duration: "7–8 hours walking",
    distance: "Approximately 15–17 km",
    meals: "Breakfast, lunch & dinner",
    stay: "Premium lodge, Namche Bazaar",
    body: "A long scenic descent: alpine to forest, Sherpa villages, the Dudh Koshi again, then the rise into Namche after 7–8 hours.\n\nCelebrate the Base Camp section over a comfortable meal. The horseshoe town feels generous after the glacier.",
  },
  {
    id: "d13",
    day: 13,
    title: "Namche Bazaar to Lukla",
    altitude: "2,860 m / 9,383 ft",
    duration: "7–8 hours walking",
    distance: "Approximately 17–19 km",
    meals: "Breakfast, lunch & dinner",
    stay: "Premium / best available lodge, Lukla",
    body: "Last walking day: down from Namche, prayer-flag bridges, Phakding, the final rise into Lukla after 7–8 hours.\n\nLodge dinner with guide and team. Sleep early — the flight window is weather-owned and usually at first light.",
  },
  {
    id: "d14",
    day: 14,
    title: "Fly Lukla to Kathmandu – private transfer & trip ends",
    altitude: "1,300 m / 4,265 ft",
    duration: "Mountain flight + transfer",
    distance: "Lukla → Kathmandu",
    meals: "Breakfast",
    stay: "Hotel or onward, Kathmandu",
    body: "Scenic flight out of Tenzing-Hillary Airport. One last aerial look at the valleys you walked.\n\nPrivate transfer to your hotel or the international terminal if you fly the same day. Extra days in Nepal — heritage, wildlife, mountain flight — can be held if you ask before booking.\n\nThe luxury trek concludes in Kathmandu.",
  },
];

export const EBC_INCLUSIONS = [
  "Airport pick-up and drop with a private car or van and an Ambition Holidays representative.",
  "Four nights in Kathmandu in a 5-star hotel with breakfast.",
  "Kathmandu–Lukla–Kathmandu flights on a Twin Otter (or equivalent), including domestic taxes.",
  "Five nights at Yeti Mountain Home or the same category in Lukla, Phakding and Namche.",
  "From Tengboche upward: the best available lodge in each village.",
  "A Kathmandu day tour by private deluxe vehicle with a guide, including sightseeing entrance fees.",
  "All necessary trekking permits and documents.",
  "Breakfast, lunch, dinner, plus tea, coffee or hot water on trek days.",
  "Wi-Fi, battery charging and hot showers as listed on trek days.",
  "Seasonal fruit after the evening meal where available.",
  "Well-trained trekking guides: salary, transport, food, lodging and insurance.",
  "Assistant guide for groups of more than six (salary, lodging, meals, insurance).",
  "Porters throughout (one porter per two guests), including salary, food, lodging and transport.",
  "Down jacket, sleeping bag and duffel for use on the trek.",
  "Ambition Himalaya T-shirt and a trek map.",
  "First-aid kit carried by the guiding team.",
  "Expedition taxes, paperwork and company service charges.",
  "Traditional welcome dinner in a Nepali restaurant on arrival.",
  "Complimentary one-hour spa (massage).",
  "Worst-case helicopter rescue coordination (funded by your travel insurance).",
  "Certificate of achievement signed by the company director and your local guide, if requested.",
];

export const EBC_EXCLUSIONS = [
  "International airfares.",
  "Nepal visa fees (USD 30 / 15 days, USD 50 / 30 days, USD 125 / 90 days — subject to official change).",
  "Travel insurance and emergency rescue cover (mandatory).",
  "Bar drinks, beverages and bottled mineral water.",
  "Activities not listed in the itinerary, and extra porter charges.",
  "Kathmandu lunches and dinners, including if you return early from the trail.",
  "Extra costs from natural events, flight delay, or early arrival.",
  "Tips and gratuities for guide and porters.",
  "Any benefit not listed under What’s included, unless confirmed at booking.",
];

export const EBC_ADDONS = [
  "Extra days on the trail or in Kathmandu.",
  "Helicopter flight to Lukla and back.",
];

export const EBC_INCLUDE_NOTE =
  "A safe Lukla flight starts this journey. Weather can delay or cancel. If you wish, we can try to book a helicopter — typically about USD 400–600 per person depending on load. Some itineraries already hold a spare day. We strongly suggest extra days at the end of your holiday; delays can last more than one morning.";

export const EBC_LUKLA_NOTE =
  "In peak seasons, Lukla flights may use Ramechhap instead of Kathmandu to ease congestion. That means a 135 km road transfer each way. Private transport is included. We confirm the airport at your Thamel briefing.";
