import type { NepalContent, NepalPackage } from "@/lib/nepal-defaults";

const CONTACT = "/contact";

function pkg(
  id: string,
  title: string,
  days: number,
  imageSrc: string,
  imageAlt: string,
  subtitle: string,
  difficulty: string,
  description: string,
  badge: string,
): NepalPackage {
  return {
    id,
    title,
    days,
    subtitle,
    difficulty,
    description,
    badge,
    href: `${CONTACT}?interest=${id}`,
    imageSrc,
    imageAlt,
  };
}

export const DEFAULT_MULTI: NepalContent = {
  visible: true,
  coverSrc: "/images/multi/multi-cover.webp",
  wallpaperSrc: "/images/multi/multi-cover.webp",
  eyebrow: "Destination",
  headline: "Multi-Country",
  coverLead: "One journey, many kingdoms — Nepal, Bhutan and Tibet on a private Himalayan line.",
  catalogEyebrow: "Private journeys",
  catalogHeadline: "Luxury Himalayan Multi-Country Packages",
  catalogLead:
    "Eight handcrafted itineraries — dual-country tours and three-kingdom grand circuits across Nepal, Bhutan and Tibet.",
  tabHint: "",
  ctaLabel: "Plan this journey",
  ctaHref: CONTACT,
  closeTitle: "Craft it privately",
  closeBody:
    "Ambition Holidays designs every multi-country Himalayan journey from Thamel, Kathmandu — sister company of Ambition Himalaya Treks and Expeditions. We sequence Nepal, Bhutan and Tibet permits, lodges and overland days as one private itinerary.",
  metaTitle: "Himalayan Multi-Country Luxury Tours | Ambition Holidays",
  metaDescription:
    "Luxury Nepal, Bhutan and Tibet combination tours by Ambition Holidays — dual-country itineraries and grand Himalayan circuits. Sister company of Ambition Himalaya Treks and Expeditions.",
  categories: [
    {
      id: "dual",
      label: "Luxury Dual-Country",
      countLabel: "3 Packages",
      packages: [
        pkg(
          "nepal-bhutan-lux",
          "Nepal & Bhutan Luxury Tour",
          10,
          "/images/multi/multi-nepal-bhutan.webp",
          "Nepal lakeside mountains and Bhutan cliff monastery",
          "Kathmandu valley, then the Kingdom of Happiness",
          "Easy",
          "Kathmandu and Pokhara light, then Paro and Thimphu lodges on a private ten-day line.",
          "Most Popular",
        ),
        pkg(
          "nepal-tibet-lux",
          "Nepal & Tibet Luxury Overland Journey",
          11,
          "/images/multi/multi-nepal-tibet.webp",
          "Friendship Highway from Tibet toward Nepal Himalaya",
          "Friendship Highway, Lhasa to Kathmandu",
          "Moderate",
          "Lhasa and the high plateau, then the classic overland descent into Kathmandu.",
          "Best Seller",
        ),
        pkg(
          "bhutan-tibet-lux",
          "Bhutan & Tibet Luxury Journey",
          14,
          "/images/multi/multi-bhutan-tibet.webp",
          "Bhutan cliff monastery and Tibetan palace at dusk",
          "Dzongs, then the Roof of the World",
          "Moderate",
          "Bhutan’s dzongs and lodges, then Lhasa’s palaces on a private two-kingdom itinerary.",
          "Exclusive",
        ),
      ],
    },
    {
      id: "grand",
      label: "Luxury Three Kingdoms",
      countLabel: "5 Packages",
      packages: [
        pkg(
          "nbt-lux",
          "Nepal, Bhutan & Tibet Luxury Journey",
          18,
          "/images/multi/multi-nbt.webp",
          "Himalayan peaks, cliff monastery and plateau light",
          "Three kingdoms, one private line",
          "Moderate",
          "Nepal, Bhutan and Tibet in eighteen days — lodges, dzongs and the high plateau.",
          "Most Popular",
        ),
        pkg(
          "grand-lux",
          "Nepal, Tibet & Bhutan Grand Luxury Tour",
          21,
          "/images/multi/multi-grand.webp",
          "Grand Himalayan kingdoms palaces lakes and peaks",
          "A longer three-kingdom luxury circuit",
          "Moderate",
          "Twenty-one days across Nepal, Tibet and Bhutan with extra rest and lodge nights.",
          "Best Seller",
        ),
        pkg(
          "circuit-lux",
          "Himalayan Kingdoms Luxury Circuit",
          15,
          "/images/multi/multi-circuit.webp",
          "Himalayan kingdoms circuit of lakes dzongs and peaks",
          "A tighter circuit of the three kingdoms",
          "Moderate",
          "Fifteen days circling the Himalayan kingdoms — culture first, high passes second.",
          "Hidden Gem",
        ),
        pkg(
          "explorer-lux",
          "Nepal, Bhutan & Tibet Grand Explorer",
          20,
          "/images/multi/multi-explorer.webp",
          "Vast Himalayan panorama for a grand explorer journey",
          "Deeper time in each kingdom",
          "Moderate",
          "Twenty days to explore Nepal, Bhutan and Tibet with slower pacing and private guiding.",
          "Exclusive",
        ),
        pkg(
          "ultimate-lux",
          "Ultimate Himalaya Luxury Journey",
          24,
          "/images/multi/multi-ultimate.webp",
          "Ultimate Himalaya snow massifs and high plateau",
          "The longest private Himalayan circuit",
          "Challenging",
          "Twenty-four days — the full luxury Himalaya: Nepal trails, Bhutan lodges and Tibet’s plateau.",
          "Exclusive",
        ),
      ],
    },
  ],
};
