import type { NepalContent, NepalPackage } from "@/lib/nepal-defaults";

const CONTACT = "/contact";

function pkg(
  id: string,
  title: string,
  days: number,
  imageSrc: string,
  imageAlt: string,
  subtitle: string,
  difficulty: string,
  description: string,
  badge: string,
): NepalPackage {
  return {
    id,
    title,
    days,
    subtitle,
    difficulty,
    description,
    badge,
    href: `${CONTACT}?interest=${id}`,
    imageSrc,
    imageAlt,
  };
}

export const DEFAULT_TIBET: NepalContent = {
  visible: true,
  coverSrc: "/images/tibet/tibet-cover.webp",
  wallpaperSrc: "/images/tibet/tibet-cover.webp",
  eyebrow: "Destination",
  headline: "Tibet",
  coverLead: "Luxury journeys across the Roof of the World — Lhasa, Everest’s north face and Kailash.",
  catalogEyebrow: "Private journeys",
  catalogHeadline: "Luxury Tibet Packages",
  catalogLead:
    "Eight handcrafted itineraries — Lhasa culture, the Friendship Highway, Everest North Face and the Kailash kora.",
  tabHint: "",
  ctaLabel: "Plan this journey",
  ctaHref: CONTACT,
  closeTitle: "Craft it privately",
  closeBody:
    "Ambition Holidays designs every Tibet journey from Thamel, Kathmandu — sister company of Ambition Himalaya Treks and Expeditions. We arrange Tibet travel permits, plateau pacing and private lodges around your dates.",
  metaTitle: "Luxury Tibet Tours | Ambition Holidays",
  metaDescription:
    "Luxury Tibet packages by Ambition Holidays: Lhasa, Yamdrok, Everest North Face, Shigatse and Mount Kailash. Sister company of Ambition Himalaya Treks and Expeditions.",
  categories: [
    {
      id: "cultural",
      label: "Luxury Cultural Journeys",
      countLabel: "3 Packages",
      packages: [
        pkg(
          "yamdrok-lux",
          "Lhasa & Yamdrok Lake Luxury Tour",
          5,
          "/images/tibet/tibet-yamdrok.webp",
          "Turquoise Yamdrok Lake and snow peaks in Tibet",
          "Potala, Jokhang and the turquoise lake",
          "Easy",
          "Lhasa’s palaces and a private day at Yamdrok’s turquoise shore.",
          "Most Popular",
        ),
        pkg(
          "lhasa-heritage-lux",
          "Lhasa Cultural Heritage Luxury Tour",
          6,
          "/images/tibet/tibet-heritage.webp",
          "Jokhang Temple golden roofs on the Barkhor in Lhasa",
          "Barkhor, Jokhang and the Potala",
          "Easy",
          "A slower Lhasa — Jokhang, Barkhor and Potala with heritage-hotel nights.",
          "Best Seller",
        ),
        pkg(
          "lhasa-ktm-lux",
          "Lhasa to Kathmandu Luxury Overland Journey",
          7,
          "/images/tibet/tibet-overland.webp",
          "Friendship Highway across the Tibetan plateau toward Nepal",
          "Friendship Highway to Nepal",
          "Moderate",
          "The classic overland line from Lhasa down the Friendship Highway to Kathmandu.",
          "Exclusive",
        ),
      ],
    },
    {
      id: "peaks",
      label: "Luxury Everest & Kailash",
      countLabel: "5 Packages",
      packages: [
        pkg(
          "lhasa-ebc-lux",
          "Lhasa to Everest Base Camp Luxury Tour",
          8,
          "/images/tibet/tibet-ebc.webp",
          "Everest North Face from the Tibetan plateau",
          "Rongbuk and the north base",
          "Moderate",
          "Lhasa to Rongbuk and Everest’s north base, paced with private plateau nights.",
          "Most Popular",
        ),
        pkg(
          "north-face-lux",
          "Everest North Face Luxury Adventure",
          8,
          "/images/tibet/tibet-northface.webp",
          "Close view of Everest North Face and Rongbuk glacier",
          "North face close to the icefall",
          "Moderate",
          "A focused north-face window — glacier light, Rongbuk and the wall of Everest.",
          "Best Seller",
        ),
        pkg(
          "shigatse-everest-lux",
          "Lhasa, Shigatse & Everest Luxury Journey",
          10,
          "/images/tibet/tibet-shigatse.webp",
          "Tashilhunpo monastery in Shigatse with Himalayan light",
          "Tashilhunpo, then the north face",
          "Moderate",
          "Lhasa, Tashilhunpo in Shigatse, then the north approach to Everest.",
          "Hidden Gem",
        ),
        pkg(
          "kailash-lux",
          "Mount Kailash & Lake Manasarovar Luxury Journey",
          15,
          "/images/tibet/tibet-kailash.webp",
          "Mount Kailash pyramid peak and Lake Manasarovar",
          "Sacred kora and the turquoise lake",
          "Challenging",
          "Kailash kora and Manasarovar at a luxury pace, with private high-plateau support.",
          "Exclusive",
        ),
        pkg(
          "kailash-everest-lux",
          "Kailash, Manasarovar & Everest Luxury Journey",
          16,
          "/images/tibet/tibet-kailash-everest.webp",
          "Kailash and distant Everest on the Tibetan plateau",
          "Two sacred peaks, one plateau line",
          "Challenging",
          "Kailash, Manasarovar and Everest’s north face on one private plateau itinerary.",
          "Exclusive",
        ),
      ],
    },
  ],
};
